apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdnsadmin.fullname" . }}
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type "LoadBalancer" -}}externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}{{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "powerdnsadmin.selectorLabels" . | nindent 4 }}
